---@meta
---@diagnostic disable: missing-return, unused-local, duplicate-set-field

-- Generated by scripts/generate_graven_lib.py. Do not edit this file directly.
-- Graven Lua API definitions for Lua Language Server / EmmyLua.
-- This file is metadata only. Do not execute or require it from a script package.

---@alias GravenArgb integer
---@alias GravenDirection
---| "down"
---| "up"
---| "north"
---| "south"
---| "west"
---| "east"
---@alias GravenJsonValue boolean|number|string|GravenJsonArray|GravenJsonObject
---@alias GravenEventId
---| "client_tick.pre"
---| "client_tick.post"
---| "packet.send"
---| "packet.receive"
---| "player_tick.pre"
---| "player_tick.post"
---| "render2d.level"
---| "render2d.hud"
---| "render3d"
---@alias GravenEventClassName
---| "AfterRender3DEvent"
---| "AttackEntityEvent"
---| "AttackSlowDownEvent"
---| "AttackYawEvent"
---| "BlockCollisionEvent"
---| "ChunkOcclusionEvent"
---| "ClientTickEvent.Pre"
---| "ClientTickEvent.Post"
---| "DestroyBlockEvent"
---| "FallFlyingEvent"
---| "FireworkRotationEvent"
---| "GameJoinedEvent"
---| "GameLeftEvent"
---| "JumpEvent"
---| "KeyboardInputEvent"
---| "KeyPressEvent"
---| "LevelUpdateEvent"
---| "MousePressEvent"
---| "MouseScrollEvent"
---| "MoveEvent"
---| "OpenScreenEvent"
---| "PacketEvent.Send"
---| "PacketEvent.Receive"
---| "PlayerTickEvent.Pre"
---| "PlayerTickEvent.Post"
---| "RaytraceEvent"
---| "Render2DEvent.Level"
---| "Render2DEvent.HUD"
---| "Render3DEvent"
---| "RespawnEvent"
---| "RightClickEvent"
---| "RotationAnimationEvent"
---| "SendPositionEvent"
---| "SlowdownEvent"
---| "StartDestroyBlockEvent"
---| "StartUseItemEvent"
---| "StrafeEvent"
---| "SwingHandEvent"
---| "TravelEvent"
---| "UseItemEvent"
---| "UseItemRaytraceEvent"
---@alias GravenUtilClassName
---| "BlockRegistryUtils"
---| "BlockUtils"
---| "ChatUtils"
---| "ClickSlotUtils"
---| "ClientUtils"
---| "ColorUtils"
---| "DamageUtils"
---| "EnchantmentUtils"
---| "HoleUtils"
---| "InteractionUtils"
---| "InvUtils"
---| "KeybindUtils"
---| "MathUtils"
---| "MoveUtils"
---| "PacketUtils"
---| "PlayerUtils"
---| "RaytraceUtils"
---| "RotationUtils"
---| "ScissorUtils"
---| "TimerUtils"
---| "WorldToScreen"
---@alias GravenEventCallback fun(event: userdata)
---@alias GravenRender2DCallback fun(ui: GravenUiContext, event: userdata)
---@alias GravenRender3DCallback fun(render3d: GravenRender3DContext, event: userdata)

---@class GravenJsonArray: table<integer, GravenJsonValue>

---@class GravenJsonObject: table<string, GravenJsonValue>

---@class GravenLuaJava
local LuaJava = {}

---Binds a fully qualified Java class name.
---@overload fun(className: "tech.hakuri.graven.utils.combat.DamageUtils$ArmorEnchantmentMode"): GravenJavaDamageUtilsArmorEnchantmentModeClass
---@param className string
---@return userdata javaClass
function LuaJava.bindClass(className) end

---Binds an Graven event class by its short registry name.
---@param eventName GravenEventClassName
---@return userdata javaClass
function LuaJava.bindEventClass(eventName) end

---Binds an explicitly registered Graven utility class by its short name.
---@overload fun(utilName: "BlockRegistryUtils"): GravenJavaBlockRegistryUtilsClass
---@overload fun(utilName: "BlockUtils"): GravenJavaBlockUtilsClass
---@overload fun(utilName: "ChatUtils"): GravenJavaChatUtilsClass
---@overload fun(utilName: "ClickSlotUtils"): GravenJavaClickSlotUtilsClass
---@overload fun(utilName: "ClientUtils"): GravenJavaClientUtilsClass
---@overload fun(utilName: "ColorUtils"): GravenJavaColorUtilsClass
---@overload fun(utilName: "DamageUtils"): GravenJavaDamageUtilsClass
---@overload fun(utilName: "EnchantmentUtils"): GravenJavaEnchantmentUtilsClass
---@overload fun(utilName: "HoleUtils"): GravenJavaHoleUtilsClass
---@overload fun(utilName: "InteractionUtils"): GravenJavaInteractionUtilsClass
---@overload fun(utilName: "InvUtils"): GravenJavaInvUtilsClass
---@overload fun(utilName: "KeybindUtils"): GravenJavaKeybindUtilsClass
---@overload fun(utilName: "MathUtils"): GravenJavaMathUtilsClass
---@overload fun(utilName: "MoveUtils"): GravenJavaMoveUtilsClass
---@overload fun(utilName: "PacketUtils"): GravenJavaPacketUtilsClass
---@overload fun(utilName: "PlayerUtils"): GravenJavaPlayerUtilsClass
---@overload fun(utilName: "RaytraceUtils"): GravenJavaRaytraceUtilsClass
---@overload fun(utilName: "RotationUtils"): GravenJavaRotationUtilsClass
---@overload fun(utilName: "ScissorUtils"): GravenJavaScissorUtilsClass
---@overload fun(utilName: "TimerUtils"): GravenJavaTimerUtilsClass
---@overload fun(utilName: "WorldToScreen"): GravenJavaWorldToScreenClass
---@param utilName GravenUtilClassName
---@return userdata javaClass
function LuaJava.bindUtilClass(utilName) end

---Creates a Java object from a fully qualified class name.
---@overload fun(className: "tech.hakuri.graven.utils.world.BlockUtils"): GravenJavaBlockUtils
---@overload fun(className: "tech.hakuri.graven.utils.player.ChatUtils"): GravenJavaChatUtils
---@overload fun(className: "tech.hakuri.graven.utils.player.ClickSlotUtils"): GravenJavaClickSlotUtils
---@overload fun(className: "tech.hakuri.graven.utils.client.ClientUtils"): GravenJavaClientUtils
---@overload fun(className: "tech.hakuri.graven.utils.render.ColorUtils"): GravenJavaColorUtils
---@overload fun(className: "tech.hakuri.graven.utils.player.EnchantmentUtils"): GravenJavaEnchantmentUtils
---@overload fun(className: "tech.hakuri.graven.utils.world.hole.HoleUtils"): GravenJavaHoleUtils
---@overload fun(className: "tech.hakuri.graven.utils.player.InteractionUtils"): GravenJavaInteractionUtils
---@overload fun(className: "tech.hakuri.graven.utils.player.InvUtils"): GravenJavaInvUtils
---@overload fun(className: "tech.hakuri.graven.utils.player.MoveUtils"): GravenJavaMoveUtils
---@overload fun(className: "tech.hakuri.graven.utils.network.PacketUtils"): GravenJavaPacketUtils
---@overload fun(className: "tech.hakuri.graven.utils.player.PlayerUtils"): GravenJavaPlayerUtils
---@overload fun(className: "tech.hakuri.graven.utils.rotation.RaytraceUtils"): GravenJavaRaytraceUtils
---@overload fun(className: "tech.hakuri.graven.utils.rotation.RotationUtils"): GravenJavaRotationUtils
---@overload fun(className: "tech.hakuri.graven.utils.timer.TimerUtils"): GravenJavaTimerUtils
---@param className string
---@param ... any
---@return userdata javaObject
function LuaJava.newInstance(className, ...) end

---Creates a Java object from a class returned by bindClass or bindUtilClass.
---@overload fun(javaClass: GravenJavaBlockUtilsClass): GravenJavaBlockUtils
---@overload fun(javaClass: GravenJavaChatUtilsClass): GravenJavaChatUtils
---@overload fun(javaClass: GravenJavaClickSlotUtilsClass): GravenJavaClickSlotUtils
---@overload fun(javaClass: GravenJavaClientUtilsClass): GravenJavaClientUtils
---@overload fun(javaClass: GravenJavaColorUtilsClass): GravenJavaColorUtils
---@overload fun(javaClass: GravenJavaEnchantmentUtilsClass): GravenJavaEnchantmentUtils
---@overload fun(javaClass: GravenJavaHoleUtilsClass): GravenJavaHoleUtils
---@overload fun(javaClass: GravenJavaInteractionUtilsClass): GravenJavaInteractionUtils
---@overload fun(javaClass: GravenJavaInvUtilsClass): GravenJavaInvUtils
---@overload fun(javaClass: GravenJavaMoveUtilsClass): GravenJavaMoveUtils
---@overload fun(javaClass: GravenJavaPacketUtilsClass): GravenJavaPacketUtils
---@overload fun(javaClass: GravenJavaPlayerUtilsClass): GravenJavaPlayerUtils
---@overload fun(javaClass: GravenJavaRaytraceUtilsClass): GravenJavaRaytraceUtils
---@overload fun(javaClass: GravenJavaRotationUtilsClass): GravenJavaRotationUtils
---@overload fun(javaClass: GravenJavaTimerUtilsClass): GravenJavaTimerUtils
---@param javaClass userdata
---@param ... any
---@return userdata javaObject
LuaJava["new"] = function(javaClass, ...) end

---Creates a Java proxy. Interface names precede the implementation table.
---@param ... string|table
---@return userdata javaProxy
function LuaJava.createProxy(...) end

---Invokes a public static no-argument Java library loader.
---@param className string
---@param methodName string
---@return any
function LuaJava.loadLib(className, methodName) end

---@class GravenStorage
local Storage = {}

---Returns nil when the key does not exist.
---@param key string
---@return GravenJsonValue|nil value
function Storage:get(key) end

---Stores a JSON-compatible value. Use remove to delete a key.
---@param key string
---@param value GravenJsonValue
function Storage:set(key, value) end

---@param key string
function Storage:remove(key) end

function Storage:clear() end

---@class GravenSettingHandle<T>
---@field id string
---@field owner string
local SettingHandle = {}

---@return T value
function SettingHandle:get() end

---@param value T
---@return T normalizedValue
function SettingHandle:set(value) end

---@return userdata javaSetting
function SettingHandle:java_setting() end

---@class GravenSettingSpec
---@field id string Lowercase stable ID.
---@field group? string Group ID returned by group().
---@field available? fun(): boolean

---@class GravenBoolSettingSpec: GravenSettingSpec
---@field default boolean
---@field changed? fun(value: boolean)

---@class GravenIntSettingSpec: GravenSettingSpec
---@field default integer
---@field min integer
---@field max integer
---@field step integer
---@field changed? fun(value: integer)

---@class GravenDoubleSettingSpec: GravenSettingSpec
---@field default number
---@field min number
---@field max number
---@field step number
---@field changed? fun(value: number)

---@class GravenStringSettingSpec: GravenSettingSpec
---@field default string
---@field changed? fun(value: string)

---@class GravenChoiceSettingSpec: GravenSettingSpec
---@field default string
---@field choices string[]
---@field changed? fun(value: string)

---@class GravenColorSettingSpec: GravenSettingSpec
---@field default GravenArgb
---@field allowAlpha? boolean Defaults to true.

---@class GravenKeybindSettingSpec: GravenSettingSpec
---@field default integer GLFW key code.

---@class GravenStringListSettingSpec: GravenSettingSpec
---@field default string[]

---@class GravenSettingHostApi
local SettingHostApi = {}

---Declares a setting group. Only valid during an entrypoint's declaration phase.
---@param id string
---@return string groupId
function SettingHostApi:group(id) end

---Finds a setting already declared on this host.
---@param id string
---@return GravenSettingHandle<any>
function SettingHostApi:setting(id) end

---@param spec GravenBoolSettingSpec
---@return GravenSettingHandle<boolean>
function SettingHostApi:boolSetting(spec) end

---@param spec GravenIntSettingSpec
---@return GravenSettingHandle<integer>
function SettingHostApi:intSetting(spec) end

---@param spec GravenDoubleSettingSpec
---@return GravenSettingHandle<number>
function SettingHostApi:doubleSetting(spec) end

---@param spec GravenStringSettingSpec
---@return GravenSettingHandle<string>
function SettingHostApi:stringSetting(spec) end

---@param spec GravenChoiceSettingSpec
---@return GravenSettingHandle<string>
function SettingHostApi:choiceSetting(spec) end

---@param spec GravenColorSettingSpec
---@return GravenSettingHandle<GravenArgb>
function SettingHostApi:colorSetting(spec) end

---@param spec GravenKeybindSettingSpec
---@return GravenSettingHandle<integer>
function SettingHostApi:keybindSetting(spec) end

---@param spec GravenStringListSettingSpec
---@return GravenSettingHandle<string[]>
function SettingHostApi:stringListSetting(spec) end

---@class GravenAddonApi: GravenSettingHostApi
local AddonApi = {}

---@class GravenModuleApi: GravenSettingHostApi
---@field readonly storage GravenStorage
local ModuleApi = {}

---@param callback fun()
function ModuleApi:on_enable(callback) end

---@param callback fun()
function ModuleApi:on_disable(callback) end

---@param callback fun()
function ModuleApi:on_cleanup(callback) end

---@overload fun(self: GravenModuleApi, eventId: "render2d.level"|"render2d.hud", priority: integer, callback: GravenRender2DCallback)
---@overload fun(self: GravenModuleApi, eventId: "render3d", priority: integer, callback: GravenRender3DCallback)
---@param eventId GravenEventId
---@param priority integer Render3D priorities must be greater than -999.
---@param callback GravenEventCallback
function ModuleApi:on(eventId, priority, callback) end

---@param eventClass userdata A class returned by luajava.bindEventClass or bindClass.
---@param priority integer Render3D priorities must be greater than -999.
---@param callback GravenEventCallback|GravenRender2DCallback|GravenRender3DCallback
function ModuleApi:on_class(eventClass, priority, callback) end

---@return userdata javaModule
function ModuleApi:java_module() end

---@class GravenPackageApi
---@field id string
---@field version string
---@field directory string
---@field packageStorage GravenStorage
local PackageApi = {}

---@class GravenUiContext
local UiContext = {}

---@param x number
---@param y number
---@param width number
---@param height number
---@param color GravenArgb
function UiContext:rect(x, y, width, height, color) end

---@param x number
---@param y number
---@param width number
---@param height number
---@param radius number
---@param color GravenArgb
function UiContext:round_rect(x, y, width, height, radius, color) end

---@param x number
---@param y number
---@param width number
---@param height number
---@param radius number
---@param thickness number
---@param color GravenArgb
function UiContext:outline(x, y, width, height, radius, thickness, color) end

---@param x number
---@param y number
---@param width number
---@param height number
---@param radius number
---@param blur number
---@param color GravenArgb
function UiContext:shadow(x, y, width, height, radius, blur, color) end

---@param text string
---@param x number
---@param y number
---@param scale number
---@param color GravenArgb
---@param font? string
function UiContext:text(text, x, y, scale, color, font) end

---Pass nil for font when using the default font with rotation.
---@param text string
---@param x number
---@param y number
---@param scale number
---@param color GravenArgb
---@param font string|nil
---@param angle number
---@param pivotX number
---@param pivotY number
function UiContext:rotated_text(text, x, y, scale, color, font, angle, pivotX, pivotY) end

---@param resource string
---@param x number
---@param y number
---@param width number
---@param height number
---@param color GravenArgb
function UiContext:texture(resource, x, y, width, height, color) end

---@param x number
---@param y number
---@param size number
---@param angle number
---@param color GravenArgb
function UiContext:triangle(x, y, size, angle, color) end

---@param layer integer
---@param callback fun(child: GravenUiContext)
function UiContext:layer(layer, callback) end

---@param x number
---@param y number
---@param width number
---@param height number
---@param callback fun(child: GravenUiContext)
function UiContext:scissor(x, y, width, height, callback) end

---@param x number
---@param y number
---@param width number
---@param height number
---@param callback fun(child: GravenUiContext)
function UiContext:push_absolute(x, y, width, height, callback) end

---@param text string
---@param scale number
---@param font? string
---@return number width
function UiContext:text_width(text, scale, font) end

---@param scale number
---@param font? string
---@return number height
function UiContext:text_height(scale, font) end

---@return userdata uiTreeScope
function UiContext:raw_scope() end

---@class GravenRender3DContext
local Render3DContext = {}

---@param box userdata A net.minecraft.world.phys.AABB.
---@param color GravenArgb
function Render3DContext:filled_box(box, color) end

---@param box userdata A net.minecraft.world.phys.AABB.
---@param bottomColor GravenArgb
---@param topColor GravenArgb
function Render3DContext:filled_fade_box(box, bottomColor, topColor) end

---@param box userdata A net.minecraft.world.phys.AABB.
---@param blurStrength number
function Render3DContext:blurred_box(box, blurStrength) end

---@param box userdata A net.minecraft.world.phys.AABB.
---@param color GravenArgb
---@param direction GravenDirection|userdata
function Render3DContext:filled_side(box, color, direction) end

---@param box userdata A net.minecraft.world.phys.AABB.
---@param color GravenArgb
---@param thickness number
function Render3DContext:outline_box(box, color, thickness) end

---@param box userdata A net.minecraft.world.phys.AABB.
---@param color GravenArgb
---@param thickness number
---@param direction GravenDirection|userdata
function Render3DContext:side_outline(box, color, thickness, direction) end

---@param from userdata A net.minecraft.world.phys.Vec3.
---@param to userdata A net.minecraft.world.phys.Vec3.
---@param color GravenArgb
---@param thickness number
function Render3DContext:line(from, to, color, thickness) end

---@param minX number
---@param minY number
---@param minZ number
---@param maxX number
---@param maxY number
---@param maxZ number
---@return userdata box A net.minecraft.world.phys.AABB.
function Render3DContext:box(minX, minY, minZ, maxX, maxY, maxZ) end

---@param x number
---@param y number
---@param z number
---@return userdata vector A net.minecraft.world.phys.Vec3.
function Render3DContext:vec3(x, y, z) end

---@return userdata scheduler A Render3DScheduler.
function Render3DContext:raw_scheduler() end

---Java utility: `tech.hakuri.graven.utils.world.BlockRegistryUtils`.
---@class GravenJavaBlockRegistryUtilsClass
local JavaBlockRegistryUtilsClass = {}

---@return userdata value Java type: `List<Block>`.
function JavaBlockRegistryUtilsClass:allSelectableBlocks() end

---@param block userdata Java type: `Block`.
---@return boolean value Java type: `boolean`.
function JavaBlockRegistryUtilsClass:isSelectable(block) end

---@param block userdata Java type: `Block`.
---@return string value Java type: `String`.
function JavaBlockRegistryUtilsClass:id(block) end

---@param id string Java type: `String`.
---@return userdata value Java type: `Block`.
function JavaBlockRegistryUtilsClass:byId(id) end

---@param block userdata Java type: `Block`.
---@return string value Java type: `String`.
function JavaBlockRegistryUtilsClass:displayName(block) end

---@param block userdata Java type: `Block`.
---@return string value Java type: `String`.
function JavaBlockRegistryUtilsClass:searchText(block) end

---@param blocks userdata Java type: `Collection<Block>`.
---@return userdata value Java type: `List<String>`.
function JavaBlockRegistryUtilsClass:toIds(blocks) end

---Java utility: `tech.hakuri.graven.utils.world.BlockUtils`.
---@class GravenJavaBlockUtils
local JavaBlockUtils = {}

---@class GravenJavaBlockUtilsClass
local JavaBlockUtilsClass = {}

---@param pos userdata Java type: `BlockPos`.
---@return boolean value Java type: `boolean`.
function JavaBlockUtilsClass:canPlaceAt(pos) end

---Java utility: `tech.hakuri.graven.utils.player.ChatUtils`.
---@class GravenJavaChatUtils
local JavaChatUtils = {}

---@class GravenJavaChatUtilsClass
---@field readonly PREFIX string Java type: `String`.
local JavaChatUtilsClass = {}

---@overload fun(self: GravenJavaChatUtilsClass, message: userdata)
---@overload fun(self: GravenJavaChatUtilsClass, prefix: boolean, message: string)
---@overload fun(self: GravenJavaChatUtilsClass, prefix: boolean, message: userdata)
---@overload fun(self: GravenJavaChatUtilsClass, message: string, hash: integer)
---@overload fun(self: GravenJavaChatUtilsClass, message: userdata, hash: integer)
---@overload fun(self: GravenJavaChatUtilsClass, prefix: boolean, message: string, hash: integer)
---@overload fun(self: GravenJavaChatUtilsClass, prefix: boolean, message: userdata, hash: integer)
---@param message string Java type: `String`.
function JavaChatUtilsClass:addChatMessage(message) end

---@overload fun(self: GravenJavaChatUtilsClass, prefix: boolean, message: userdata): userdata
---@param prefix boolean Java type: `boolean`.
---@param message string Java type: `String`.
---@return userdata value Java type: `Component`.
function JavaChatUtilsClass:buildClientMessage(prefix, message) end

---@param original userdata Java type: `FormattedCharSequence`.
---@return userdata value Java type: `FormattedCharSequence`.
function JavaChatUtilsClass:applyAnimatedPrefix(original) end

---Java utility: `tech.hakuri.graven.utils.player.ClickSlotUtils`.
---@class GravenJavaClickSlotUtils
local JavaClickSlotUtils = {}

---@class GravenJavaClickSlotUtilsClass
local JavaClickSlotUtilsClass = {}

---@overload fun(self: GravenJavaClickSlotUtilsClass, slot: integer, button: integer, action: userdata)
---@param containerId integer Java type: `int`.
---@param slot integer Java type: `int`.
---@param button integer Java type: `int`.
---@param action userdata Java type: `ContainerInput`.
function JavaClickSlotUtilsClass:clickSlot(containerId, slot, button, action) end

---@overload fun(self: GravenJavaClickSlotUtilsClass, slot: integer)
---@param containerId integer Java type: `int`.
---@param slot integer Java type: `int`.
function JavaClickSlotUtilsClass:click(containerId, slot) end

---@overload fun(self: GravenJavaClickSlotUtilsClass, slot: integer)
---@param containerId integer Java type: `int`.
---@param slot integer Java type: `int`.
function JavaClickSlotUtilsClass:shiftClick(containerId, slot) end

---@overload fun(self: GravenJavaClickSlotUtilsClass, slot: integer)
---@param containerId integer Java type: `int`.
---@param slot integer Java type: `int`.
function JavaClickSlotUtilsClass:drop(containerId, slot) end

---@overload fun(self: GravenJavaClickSlotUtilsClass, slot: integer)
---@param containerId integer Java type: `int`.
---@param slot integer Java type: `int`.
function JavaClickSlotUtilsClass:dropAll(containerId, slot) end

---@overload fun(self: GravenJavaClickSlotUtilsClass, slot: integer, hotbarSlot: integer)
---@param containerId integer Java type: `int`.
---@param slot integer Java type: `int`.
---@param hotbarSlot integer Java type: `int`.
function JavaClickSlotUtilsClass:swap(containerId, slot, hotbarSlot) end

---Java utility: `tech.hakuri.graven.utils.client.ClientUtils`.
---@class GravenJavaClientUtils
local JavaClientUtils = {}

---@class GravenJavaClientUtilsClass
local JavaClientUtilsClass = {}

---@return boolean value Java type: `boolean`.
function JavaClientUtilsClass:isLoading() end

---Java utility: `tech.hakuri.graven.utils.render.ColorUtils`.
---@class GravenJavaColorUtils
local JavaColorUtils = {}

---@class GravenJavaColorUtilsClass
local JavaColorUtilsClass = {}

---@param color1 userdata Java type: `Color`.
---@param color2 userdata Java type: `Color`.
---@param fraction number Java type: `float`.
---@return userdata value Java type: `Color`.
function JavaColorUtilsClass:interpolateColor(color1, color2, fraction) end

---Java utility: `tech.hakuri.graven.utils.combat.DamageUtils`.
---@class GravenJavaDamageUtilsClass
---@field readonly CRYSTAL_EXPLOSION_RADIUS number Java type: `float`.
---@field readonly ANCHOR_EXPLOSION_RADIUS number Java type: `float`.
local JavaDamageUtilsClass = {}

---@param target userdata Java type: `LivingEntity`.
---@param crystalPos userdata Java type: `Vec3`.
---@param targetPos userdata Java type: `Vec3`.
---@param mode GravenJavaDamageUtilsArmorEnchantmentMode Java type: `ArmorEnchantmentMode`.
---@return number value Java type: `float`.
function JavaDamageUtilsClass:crystalDamage(target, crystalPos, targetPos, mode) end

---@param target userdata Java type: `LivingEntity`.
---@param anchorPos userdata Java type: `Vec3`.
---@param mode GravenJavaDamageUtilsArmorEnchantmentMode Java type: `ArmorEnchantmentMode`.
---@return number value Java type: `float`.
function JavaDamageUtilsClass:anchorDamage(target, anchorPos, mode) end

---@param target userdata Java type: `LivingEntity`.
---@param explosionPos userdata Java type: `Vec3`.
---@param radius number Java type: `float`.
---@param targetPos userdata Java type: `Vec3`.
---@param mode GravenJavaDamageUtilsArmorEnchantmentMode Java type: `ArmorEnchantmentMode`.
---@return number value Java type: `float`.
function JavaDamageUtilsClass:explosionDamage(target, explosionPos, radius, targetPos, mode) end

---@param target userdata Java type: `LivingEntity`.
---@param explosionPos userdata Java type: `Vec3`.
---@param radius number Java type: `float`.
---@return number value Java type: `float`.
function JavaDamageUtilsClass:rawExplosionDamage(target, explosionPos, radius) end

---@overload fun(self: GravenJavaDamageUtilsClass, center: userdata, bb: userdata, entity: userdata): number
---@param center userdata Java type: `Vec3`.
---@param entity userdata Java type: `LivingEntity`.
---@return number value Java type: `float`.
function JavaDamageUtilsClass:getSeenPercent(center, entity) end

---@overload fun(self: GravenJavaDamageUtilsClass, crystalPos: userdata, selfPos: userdata, mode: GravenJavaDamageUtilsArmorEnchantmentMode): number
---@param crystalPos userdata Java type: `Vec3`.
---@param mode GravenJavaDamageUtilsArmorEnchantmentMode Java type: `ArmorEnchantmentMode`.
---@return number value Java type: `float`.
function JavaDamageUtilsClass:selfCrystalDamage(crystalPos, mode) end

---@param entity userdata Java type: `LivingEntity`.
---@param pos userdata Java type: `Vec3`.
---@return userdata value Java type: `AABB`.
function JavaDamageUtilsClass:getPredictedBoundingBox(entity, pos) end

---Java enum: `tech.hakuri.graven.utils.combat.DamageUtils.ArmorEnchantmentMode` (`tech.hakuri.graven.utils.combat.DamageUtils$ArmorEnchantmentMode`).
---@class GravenJavaDamageUtilsArmorEnchantmentMode
local JavaDamageUtilsArmorEnchantmentMode = {}

---@class GravenJavaDamageUtilsArmorEnchantmentModeClass
---@field readonly None GravenJavaDamageUtilsArmorEnchantmentMode
---@field readonly PPPP GravenJavaDamageUtilsArmorEnchantmentMode
---@field readonly PPBP GravenJavaDamageUtilsArmorEnchantmentMode
local JavaDamageUtilsArmorEnchantmentModeClass = {}

---Java utility: `tech.hakuri.graven.utils.player.EnchantmentUtils`.
---@class GravenJavaEnchantmentUtils
local JavaEnchantmentUtils = {}

---@class GravenJavaEnchantmentUtilsClass
local JavaEnchantmentUtilsClass = {}

---@param itemStack userdata Java type: `ItemStack`.
---@param enchantments userdata Java type: `Object2IntMap<Holder<Enchantment>>`.
function JavaEnchantmentUtilsClass:getEnchantments(itemStack, enchantments) end

---@overload fun(self: GravenJavaEnchantmentUtilsClass, itemEnchantments: userdata, enchantment: userdata): integer
---@param itemStack userdata Java type: `ItemStack`.
---@param enchantment userdata Java type: `ResourceKey<Enchantment>`.
---@return integer value Java type: `int`.
function JavaEnchantmentUtilsClass:getEnchantmentLevel(itemStack, enchantment) end

---@param itemStack userdata Java type: `ItemStack`.
---@param ... userdata Java type: `ResourceKey<Enchantment>...`.
---@return boolean value Java type: `boolean`.
function JavaEnchantmentUtilsClass:hasEnchantments(itemStack, ...) end

---@param itemStack userdata Java type: `ItemStack`.
---@param enchantmentKey userdata Java type: `ResourceKey<Enchantment>`.
---@return boolean value Java type: `boolean`.
function JavaEnchantmentUtilsClass:hasEnchantment(itemStack, enchantmentKey) end

---Java utility: `tech.hakuri.graven.utils.world.hole.HoleUtils`.
---@class GravenJavaHoleUtils
local JavaHoleUtils = {}

---@class GravenJavaHoleUtilsClass
local JavaHoleUtilsClass = {}

---@overload fun(self: GravenJavaHoleUtilsClass, pos: userdata, depth: integer): userdata
---@overload fun(self: GravenJavaHoleUtilsClass, pos: userdata, depth: integer, floor: boolean): userdata
---@overload fun(self: GravenJavaHoleUtilsClass, pos: userdata, single: boolean, doubles: boolean, quad: boolean, depth: integer, floor: boolean): userdata
---@param pos userdata Java type: `BlockPos`.
---@return userdata value Java type: `Hole`.
function JavaHoleUtilsClass:getHole(pos) end

---@param pos userdata Java type: `BlockPos`.
---@return boolean value Java type: `boolean`.
function JavaHoleUtilsClass:isBlock(pos) end

---@param player userdata Java type: `Player`.
---@return boolean value Java type: `boolean`.
function JavaHoleUtilsClass:inHole(player) end

---Java utility: `tech.hakuri.graven.utils.player.InteractionUtils`.
---@class GravenJavaInteractionUtils
local JavaInteractionUtils = {}

---@class GravenJavaInteractionUtilsClass
local JavaInteractionUtilsClass = {}

---@param pos userdata Java type: `BlockPos`.
---@param rotate boolean Java type: `boolean`.
---@param hand userdata Java type: `InteractionHand`.
---@param packet boolean Java type: `boolean`.
---@param grimBypass boolean Java type: `boolean`.
---@return userdata value Java type: `InteractionResult`.
function JavaInteractionUtilsClass:airPlace(pos, rotate, hand, packet, grimBypass) end

---Java utility: `tech.hakuri.graven.utils.player.InvUtils`.
---@class GravenJavaInvUtils
local JavaInvUtils = {}

---@class GravenJavaInvUtilsClass
---@field invSlots userdata Java type: `int[]`.
---@field previousSlot integer Java type: `int`.
local JavaInvUtilsClass = {}

---@param predicate userdata Java type: `Predicate<ItemStack>`.
---@return boolean value Java type: `boolean`.
function JavaInvUtilsClass:testInMainHand(predicate) end

---@param predicate userdata Java type: `Predicate<ItemStack>`.
---@return boolean value Java type: `boolean`.
function JavaInvUtilsClass:testInOffHand(predicate) end

---@overload fun(self: GravenJavaInvUtilsClass, isGood: userdata): userdata
---@param ... userdata Java type: `Item...`.
---@return userdata value Java type: `FindItemResult`.
function JavaInvUtilsClass:findInHotbar(...) end

---@overload fun(self: GravenJavaInvUtilsClass, isGood: userdata): userdata
---@overload fun(self: GravenJavaInvUtilsClass, isGood: userdata, start: integer, end: integer): userdata
---@param ... userdata Java type: `Item...`.
---@return userdata value Java type: `FindItemResult`.
function JavaInvUtilsClass:find(...) end

---@param slot integer Java type: `int`.
---@param saveSwap boolean Java type: `boolean`.
function JavaInvUtilsClass:swap(slot, saveSwap) end

function JavaInvUtilsClass:swapBack() end

---@param slot integer Java type: `int`.
function JavaInvUtilsClass:invSwap(slot) end

function JavaInvUtilsClass:invSwapBack() end

---Java utility: `tech.hakuri.graven.utils.client.KeybindUtils`.
---@class GravenJavaKeybindUtilsClass
---@field readonly NONE integer Java type: `int`.
---@field readonly MOUSE_OFFSET integer Java type: `int`.
local JavaKeybindUtilsClass = {}

---@param keyBind integer Java type: `int`.
---@return boolean value Java type: `boolean`.
function JavaKeybindUtilsClass:isMouseButton(keyBind) end

---@param button integer Java type: `int`.
---@return integer value Java type: `int`.
function JavaKeybindUtilsClass:encodeMouseButton(button) end

---@param keyBind integer Java type: `int`.
---@return integer value Java type: `int`.
function JavaKeybindUtilsClass:decodeMouseButton(keyBind) end

---@param keyMapping userdata Java type: `KeyMapping`.
---@return integer value Java type: `int`.
function JavaKeybindUtilsClass:getKey(keyMapping) end

---@overload fun(self: GravenJavaKeybindUtilsClass, keyBind: integer): boolean
---@param keyMapping userdata Java type: `KeyMapping`.
---@return boolean value Java type: `boolean`.
function JavaKeybindUtilsClass:isPressed(keyMapping) end

---@param keyBind integer Java type: `int`.
---@return string value Java type: `String`.
function JavaKeybindUtilsClass:format(keyBind) end

---Java utility: `tech.hakuri.graven.utils.math.MathUtils`.
---@class GravenJavaMathUtilsClass
local JavaMathUtilsClass = {}

---@overload fun(self: GravenJavaMathUtilsClass, min: number, max: number): number
---@overload fun(self: GravenJavaMathUtilsClass, min: number, max: number): number
---@param min integer Java type: `int`.
---@param max integer Java type: `int`.
---@return integer value Java type: `int`.
function JavaMathUtilsClass:getRandom(min, max) end

---Java utility: `tech.hakuri.graven.utils.player.MoveUtils`.
---@class GravenJavaMoveUtils
local JavaMoveUtils = {}

---@class GravenJavaMoveUtilsClass
local JavaMoveUtilsClass = {}

---@param speed number Java type: `double`.
---@return userdata value Java type: `double[]`.
function JavaMoveUtilsClass:forwardWithoutStrafe(speed) end

---@param speed number Java type: `double`.
---@return userdata value Java type: `double[]`.
function JavaMoveUtilsClass:forward(speed) end

---Java utility: `tech.hakuri.graven.utils.network.PacketUtils`.
---@class GravenJavaPacketUtils
local JavaPacketUtils = {}

---@class GravenJavaPacketUtilsClass
---@field readonly bypassedPackets userdata Java type: `Set<Packet<?>>`.
local JavaPacketUtilsClass = {}

---@param packet userdata Java type: `Packet<?>`.
function JavaPacketUtilsClass:sendSilently(packet) end

---Java utility: `tech.hakuri.graven.utils.player.PlayerUtils`.
---@class GravenJavaPlayerUtils
local JavaPlayerUtils = {}

---@class GravenJavaPlayerUtilsClass
local JavaPlayerUtilsClass = {}

---@return boolean value Java type: `boolean`.
function JavaPlayerUtilsClass:isEating() end

---@return boolean value Java type: `boolean`.
function JavaPlayerUtilsClass:isInWeb() end

---@return boolean value Java type: `boolean`.
function JavaPlayerUtilsClass:isInBlock() end

---Java utility: `tech.hakuri.graven.utils.rotation.RaytraceUtils`.
---@class GravenJavaRaytraceUtils
local JavaRaytraceUtils = {}

---@class GravenJavaRaytraceUtilsClass
local JavaRaytraceUtilsClass = {}

---@param eyes userdata Java type: `Vec3`.
---@param vec3 userdata Java type: `Vec3`.
---@return boolean value Java type: `boolean`.
function JavaRaytraceUtilsClass:canSeePointFrom(eyes, vec3) end

---@overload fun(self: GravenJavaRaytraceUtilsClass, rotation: userdata, range: number, expand: number): userdata
---@overload fun(self: GravenJavaRaytraceUtilsClass, rotation: userdata, range: number, expand: number, entity: userdata): userdata
---@param rotation userdata Java type: `Rot2f`.
---@param range number Java type: `double`.
---@return userdata value Java type: `HitResult`.
function JavaRaytraceUtilsClass:raytrace(rotation, range) end

---@overload fun(self: GravenJavaRaytraceUtilsClass, rotation: userdata, pos: userdata, strict: boolean): boolean
---@overload fun(self: GravenJavaRaytraceUtilsClass, rotation: userdata, pos: userdata): boolean
---@overload fun(self: GravenJavaRaytraceUtilsClass, rotation: userdata, pos: userdata, enumFacing: userdata): boolean
---@param rotation userdata Java type: `Rot2f`.
---@param dir userdata Java type: `Direction`.
---@param pos userdata Java type: `BlockPos`.
---@param strict boolean Java type: `boolean`.
---@return boolean value Java type: `boolean`.
function JavaRaytraceUtilsClass:overBlock(rotation, dir, pos, strict) end

---Java utility: `tech.hakuri.graven.utils.rotation.RotationUtils`.
---@class GravenJavaRotationUtils
local JavaRotationUtils = {}

---@class GravenJavaRotationUtilsClass
local JavaRotationUtilsClass = {}

---@param pos userdata Java type: `BlockPos`.
---@return userdata value Java type: `Direction`.
function JavaRotationUtilsClass:getDirection(pos) end

---@param pos userdata Java type: `BlockPos`.
---@param side userdata Java type: `Direction`.
---@return boolean value Java type: `boolean`.
function JavaRotationUtilsClass:canSee(pos, side) end

---@param pos userdata Java type: `BlockPos`.
---@param direction userdata Java type: `Direction`.
---@return boolean value Java type: `boolean`.
function JavaRotationUtilsClass:isGrimDirection(pos, direction) end

---@param entity userdata Java type: `Entity`.
---@param fov number Java type: `float`.
---@return boolean value Java type: `boolean`.
function JavaRotationUtilsClass:isInFov(entity, fov) end

---@param entity userdata Java type: `Entity`.
---@return userdata value Java type: `Rot2f`.
function JavaRotationUtilsClass:getRotationsToEntity(entity) end

---@param entity userdata Java type: `LivingEntity`.
---@return number value Java type: `double`.
function JavaRotationUtilsClass:getEyeDistanceToEntity(entity) end

---@overload fun(self: GravenJavaRotationUtilsClass, entity: userdata): userdata
---@overload fun(self: GravenJavaRotationUtilsClass, entity: userdata, adaptive: boolean, range: number): userdata
---@overload fun(self: GravenJavaRotationUtilsClass, to: userdata): userdata
---@overload fun(self: GravenJavaRotationUtilsClass, to: userdata): userdata
---@overload fun(self: GravenJavaRotationUtilsClass, position: userdata, direction: userdata): userdata
---@overload fun(self: GravenJavaRotationUtilsClass, position: userdata, direction: userdata): userdata
---@param from userdata Java type: `Vec3`.
---@param to userdata Java type: `Vec3`.
---@return userdata value Java type: `Rot2f`.
function JavaRotationUtilsClass:calculate(from, to) end

---@overload fun(self: GravenJavaRotationUtilsClass, rotation: userdata, previousRotation: userdata): userdata
---@param rotation userdata Java type: `Rot2f`.
---@return userdata value Java type: `Rot2f`.
function JavaRotationUtilsClass:applySensitivityPatch(rotation) end

---@param rotation userdata Java type: `Rot2f`.
---@return userdata value Java type: `Rot2f`.
function JavaRotationUtilsClass:relateToPlayerRotation(rotation) end

---@param rotation userdata Java type: `Rot2f`.
---@return userdata value Java type: `Rot2f`.
function JavaRotationUtilsClass:resetRotation(rotation) end

---@overload fun(self: GravenJavaRotationUtilsClass, lastRotation: userdata, targetRotation: userdata, speed: number): userdata
---@param targetRotation userdata Java type: `Rot2f`.
---@param speed number Java type: `double`.
---@return userdata value Java type: `Rot2f`.
function JavaRotationUtilsClass:move(targetRotation, speed) end

---@overload fun(self: GravenJavaRotationUtilsClass, lastRotation: userdata, targetRotation: userdata, speed: number): userdata
---@param targetRotation userdata Java type: `Rot2f`.
---@param speed number Java type: `double`.
---@return userdata value Java type: `Rot2f`.
function JavaRotationUtilsClass:smooth(targetRotation, speed) end

---Java utility: `tech.hakuri.graven.utils.render.ScissorUtils`.
---@class GravenJavaScissorUtilsClass
local JavaScissorUtilsClass = {}

---@overload fun(self: GravenJavaScissorUtilsClass, x: number, y: number, width: number, height: number, guiHeight: number): userdata
---@overload fun(self: GravenJavaScissorUtilsClass, x: number, y: number, width: number, height: number, scale: number, framebufferHeight: integer): userdata
---@param x number Java type: `float`.
---@param y number Java type: `float`.
---@param width number Java type: `float`.
---@param height number Java type: `float`.
---@return userdata value Java type: `LuminRenderSystem.ScissorRect`.
function JavaScissorUtilsClass:toFramebufferScissor(x, y, width, height) end

---@param x integer Java type: `int`.
---@param y integer Java type: `int`.
---@param width integer Java type: `int`.
---@param height integer Java type: `int`.
---@return userdata value Java type: `LuminRenderSystem.ScissorRect`.
function JavaScissorUtilsClass:clampFramebufferScissor(x, y, width, height) end

---@overload fun(self: GravenJavaScissorUtilsClass, width: integer, height: integer): boolean
---@param scissor userdata Java type: `LuminRenderSystem.ScissorRect`.
---@return boolean value Java type: `boolean`.
function JavaScissorUtilsClass:isVisible(scissor) end

---@overload fun(self: GravenJavaScissorUtilsClass, pass: userdata, scissor: userdata): boolean
---@param pass userdata Java type: `RenderPass`.
---@param x integer Java type: `int`.
---@param y integer Java type: `int`.
---@param width integer Java type: `int`.
---@param height integer Java type: `int`.
---@return boolean value Java type: `boolean`.
function JavaScissorUtilsClass:enableScissor(pass, x, y, width, height) end

---Java utility: `tech.hakuri.graven.utils.timer.TimerUtils`.
---@class GravenJavaTimerUtils
local JavaTimerUtils = {}

function JavaTimerUtils:reset() end

---@return integer value Java type: `long`.
function JavaTimerUtils:getMs() end

---@param ms integer Java type: `long`.
function JavaTimerUtils:setMs(ms) end

---@param seconds number Java type: `double`.
---@return boolean value Java type: `boolean`.
function JavaTimerUtils:passedSecond(seconds) end

---@param ticks integer Java type: `int`.
---@return boolean value Java type: `boolean`.
function JavaTimerUtils:hasDelayed(ticks) end

---@param ms integer Java type: `long`.
---@return boolean value Java type: `boolean`.
function JavaTimerUtils:every(ms) end

---@overload fun(self: GravenJavaTimerUtils, ms: integer): boolean
---@param ms number Java type: `double`.
---@return boolean value Java type: `boolean`.
function JavaTimerUtils:passedMillise(ms) end

---@class GravenJavaTimerUtilsClass
local JavaTimerUtilsClass = {}

---Java utility: `tech.hakuri.graven.utils.render.WorldToScreen`.
---@class GravenJavaWorldToScreenClass
local JavaWorldToScreenClass = {}

---@param pos userdata Java type: `Vec3`.
---@return userdata value Java type: `Vector3f`.
function JavaWorldToScreenClass:calcWorld2ScreenRaw(pos) end

---@param pos userdata Java type: `Vec3`.
---@return userdata|nil value Java type: `Vector3f`.
function JavaWorldToScreenClass:calcWorld2Screen(pos) end

---@param pos userdata Java type: `Vec3`.
---@return number value Java type: `float`.
function JavaWorldToScreenClass:calcScale(pos) end

---@type GravenLuaJava
luajava = nil

---net.minecraft.client.Minecraft
---@type userdata
mc = nil

---Available in module entrypoints.
---@type GravenModuleApi
module = nil

---Declaration methods are only valid in settings.lua. Module entrypoints may call setting().
---@type GravenAddonApi
addon = nil

---@type GravenPackageApi
graven = nil
