org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Project
version=2026.09.01
group=tech.hakuri.graven

# Common
mod_id=graven
mod_name=Graven
mod_author=Chen_Meng, 06789
license=GPL-3.0-only
credits=
description=A powerful cheat mod for Minecraft
